repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: double-quote-string-fixer
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ['--trailing-comma', '--multi-line', '3', '--line-length', '120']
    - id: isort
      name: isort (cython)
      args: ['--trailing-comma', '--multi-line', '3', '--line-length', '120']
      types: [cython]
    - id: isort
      name: isort (pyi)
      args: ['--trailing-comma', '--multi-line', '3', '--line-length', '120']
      types: [pyi]
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'
    hooks:
    -   id: yapf
        args: ['--in-place']
-   repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
